// Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/blox/blox/cluster-state-service/handler/reconcile/loader (interfaces: ContainerInstanceLoader)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of ContainerInstanceLoader interface
type MockContainerInstanceLoader struct {
	ctrl     *gomock.Controller
	recorder *_MockContainerInstanceLoaderRecorder
}

// Recorder for MockContainerInstanceLoader (not exported)
type _MockContainerInstanceLoaderRecorder struct {
	mock *MockContainerInstanceLoader
}

func NewMockContainerInstanceLoader(ctrl *gomock.Controller) *MockContainerInstanceLoader {
	mock := &MockContainerInstanceLoader{ctrl: ctrl}
	mock.recorder = &_MockContainerInstanceLoaderRecorder{mock}
	return mock
}

func (_m *MockContainerInstanceLoader) EXPECT() *_MockContainerInstanceLoaderRecorder {
	return _m.recorder
}

func (_m *MockContainerInstanceLoader) LoadContainerInstances() error {
	ret := _m.ctrl.Call(_m, "LoadContainerInstances")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockContainerInstanceLoaderRecorder) LoadContainerInstances() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LoadContainerInstances")
}
