// Automatically generated by MockGen. DO NOT EDIT!
// Source: event/processor.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Processor interface
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *_MockProcessorRecorder
}

// Recorder for MockProcessor (not exported)
type _MockProcessorRecorder struct {
	mock *MockProcessor
}

func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &_MockProcessorRecorder{mock}
	return mock
}

func (_m *MockProcessor) EXPECT() *_MockProcessorRecorder {
	return _m.recorder
}

func (_m *MockProcessor) ProcessEvent(event string) error {
	ret := _m.ctrl.Call(_m, "ProcessEvent", event)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockProcessorRecorder) ProcessEvent(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ProcessEvent", arg0)
}
