package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*TaskOverrideModel task override model

swagger:model TaskOverrideModel
*/
type TaskOverrideModel struct {

	/* container overrides

	Required: true
	*/
	ContainerOverrides []*TaskContainerOverrideModel `json:"containerOverrides"`

	/* task role arn
	 */
	TaskRoleArn string `json:"taskRoleArn,omitempty"`
}

// Validate validates this task override model
func (m *TaskOverrideModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContainerOverrides(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskOverrideModel) validateContainerOverrides(formats strfmt.Registry) error {

	if err := validate.Required("containerOverrides", "body", m.ContainerOverrides); err != nil {
		return err
	}

	for i := 0; i < len(m.ContainerOverrides); i++ {

		if swag.IsZero(m.ContainerOverrides[i]) { // not required
			continue
		}

		if m.ContainerOverrides[i] != nil {

			if err := m.ContainerOverrides[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
