package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aws/amazon-ecs-event-stream-handler/internal/models"
)

// FilterInstancesReader is a Reader for the FilterInstances structure.
type FilterInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FilterInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewFilterInstancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewFilterInstancesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewFilterInstancesOK creates a FilterInstancesOK with default headers values
func NewFilterInstancesOK() *FilterInstancesOK {
	return &FilterInstancesOK{}
}

/*FilterInstancesOK handles this case with default header values.

Filter instances response
*/
type FilterInstancesOK struct {
	Payload []*models.ContainerInstanceModel
}

func (o *FilterInstancesOK) Error() string {
	return fmt.Sprintf("[GET /instances/filter][%d] filterInstancesOK  %+v", 200, o.Payload)
}

func (o *FilterInstancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFilterInstancesDefault creates a FilterInstancesDefault with default headers values
func NewFilterInstancesDefault(code int) *FilterInstancesDefault {
	return &FilterInstancesDefault{
		_statusCode: code,
	}
}

/*FilterInstancesDefault handles this case with default header values.

Unexpected error filtering instances
*/
type FilterInstancesDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the filter instances default response
func (o *FilterInstancesDefault) Code() int {
	return o._statusCode
}

func (o *FilterInstancesDefault) Error() string {
	return fmt.Sprintf("[GET /instances/filter][%d] FilterInstances default  %+v", o._statusCode, o.Payload)
}

func (o *FilterInstancesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
