package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aws/amazon-ecs-event-stream-handler/internal/models"
)

// GetTaskReader is a Reader for the GetTask structure.
type GetTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetTaskDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetTaskOK creates a GetTaskOK with default headers values
func NewGetTaskOK() *GetTaskOK {
	return &GetTaskOK{}
}

/*GetTaskOK handles this case with default header values.

Get task by ARN response
*/
type GetTaskOK struct {
	Payload *models.TaskModel
}

func (o *GetTaskOK) Error() string {
	return fmt.Sprintf("[GET /task/{arn}][%d] getTaskOK  %+v", 200, o.Payload)
}

func (o *GetTaskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TaskModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTaskDefault creates a GetTaskDefault with default headers values
func NewGetTaskDefault(code int) *GetTaskDefault {
	return &GetTaskDefault{
		_statusCode: code,
	}
}

/*GetTaskDefault handles this case with default header values.

Unexpected error getting task by ARN
*/
type GetTaskDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the get task default response
func (o *GetTaskDefault) Code() int {
	return o._statusCode
}

func (o *GetTaskDefault) Error() string {
	return fmt.Sprintf("[GET /task/{arn}][%d] GetTask default  %+v", o._statusCode, o.Payload)
}

func (o *GetTaskDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
