package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ContainerInstanceDetailVersionInfoModel container instance detail version info model
// swagger:model ContainerInstanceDetailVersionInfoModel
type ContainerInstanceDetailVersionInfoModel struct {

	// agent hash
	AgentHash string `json:"agentHash,omitempty"`

	// agent version
	AgentVersion string `json:"agentVersion,omitempty"`

	// docker version
	DockerVersion string `json:"dockerVersion,omitempty"`
}

// Validate validates this container instance detail version info model
func (m *ContainerInstanceDetailVersionInfoModel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
